fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

velotn:
    resource: "@VelotnBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
