fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

velotn:
    resource: "@VelotnBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fc_load_events:
    path: /fc-load-events
    defaults:
        _controller: CalendarBundle\Controller\CalendarController:loadAction
